<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser" tests="5" time="52.460" ignored="0" failures="0" timestamp="09 Sep 2020 15:31:15 GMT" skipped="0" hostname="DESKTOP-AKV4U58" errors="1">
  <testcase name="enterRequestInfo" time="11.190" classname="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser"/>
  <testcase name="modifyRequestCreated" time="4.612" classname="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.medhas.regression.ModifyOnbehalfActivedirectoryformultipleleusers.Toastmsg(ModifyOnbehalfActivedirectoryformultipleleusers.java:345)
	at com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser.modifyRequestCreated(TestModifySelfApplicationaccessforsingleuser.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- modifyRequestCreated -->
  <testcase name="checkvalidUser" time="8.776" classname="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser"/>
  <testcase name="modifyApplication" time="21.163" classname="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser"/>
  <testcase name="enterUserDetails" time="6.719" classname="com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser"/>
</testsuite> <!-- com.medhas.sanity.TestModifySelfApplicationaccessforsingleuser -->
